import React, { useState } from 'react';
import { GeneratedSong } from '../types';

interface ExportModalProps {
  song: GeneratedSong;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ song, onClose }) => {
  const [format, setFormat] = useState<'txt' | 'json' | 'markdown'>('txt');
  const [copied, setCopied] = useState(false);

  const generateTxt = () => {
    return `
${song.title}
${'='.repeat(song.title.length)}

STYLE: ${song.stylePrompt}
NEGATIVE: ${song.negativePrompt}

${song.hasAdvancedLogic ? '[Advanced Lyric Logic Enabled]\n' : ''}${song.hasMetaphorLogic ? '[Central Metaphor Logic Enabled]\n' : ''}
LYRICS:
${song.lyrics}

---

TECHNICAL NOTES:
${song.technicalExplanation}

${song.analysis ? `
ANALYSIS SCORE: ${song.analysis.overallScore}/100
${song.analysis.summary}

STRENGTHS:
${song.analysis.strengths.map(s => `• ${s}`).join('\n')}

WEAKNESSES:
${song.analysis.weaknesses.map(w => `• ${w}`).join('\n')}
` : ''}

Generated by Suno v5 Architect
Created: ${new Date(song.createdAt).toLocaleString()}
`.trim();
  };

  const generateJson = () => {
    return JSON.stringify({
      title: song.title,
      stylePrompt: song.stylePrompt,
      negativePrompt: song.negativePrompt,
      lyrics: song.lyrics,
      technicalExplanation: song.technicalExplanation,
      coverArtPrompt: song.coverArtPrompt,
      hasAdvancedLogic: song.hasAdvancedLogic,
      hasMetaphorLogic: song.hasMetaphorLogic,
      model: song.model,
      analysis: song.analysis ? {
        overallScore: song.analysis.overallScore,
        projectedScore: song.analysis.projectedScore,
        summary: song.analysis.summary,
        scoreBreakdown: song.analysis.scoreBreakdown,
        strengths: song.analysis.strengths,
        weaknesses: song.analysis.weaknesses,
        commercialViability: song.analysis.commercialViability
      } : null,
      createdAt: song.createdAt,
      audioUrl: song.audioUrl
    }, null, 2);
  };

  const generateMarkdown = () => {
    return `
# ${song.title}

## Style Information
**Style:** ${song.stylePrompt}  
**Negative Prompt:** ${song.negativePrompt}  
${song.hasAdvancedLogic ? '**Advanced Lyric Logic:** ✓\n' : ''}${song.hasMetaphorLogic ? '**Central Metaphor Logic:** ✓\n' : ''}

## Lyrics
\`\`\`
${song.lyrics}
\`\`\`

## Technical Notes
${song.technicalExplanation}

${song.analysis ? `
## Analysis
**Overall Score:** ${song.analysis.overallScore}/100  
**Projected Score:** ${song.analysis.projectedScore}/100

### Summary
${song.analysis.summary}

### Score Breakdown
${song.analysis.scoreBreakdown.map(item => `- **${item.category}:** ${item.score}/10 - ${item.reason}`).join('\n')}

### Strengths
${song.analysis.strengths.map(s => `- ${s}`).join('\n')}

### Weaknesses
${song.analysis.weaknesses.map(w => `- ${w}`).join('\n')}

### Commercial Viability
${song.analysis.commercialViability}
` : ''}

---
*Generated by Suno v5 Architect on ${new Date(song.createdAt).toLocaleString()}*
`.trim();
  };

  const getContent = () => {
    switch (format) {
      case 'txt': return generateTxt();
      case 'json': return generateJson();
      case 'markdown': return generateMarkdown();
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = getContent();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${song.title.replace(/[^a-z0-9]/gi, '_')}.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
      <div className="bg-slate-900 border border-white/20 rounded-2xl max-w-4xl w-full max-h-[90vh] flex flex-col shadow-2xl">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-white/10">
          <h3 className="text-xl font-bold text-white flex items-center gap-3">
            <svg className="w-6 h-6 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
            </svg>
            Export Song
          </h3>
          <button 
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>

        {/* Format Selector */}
        <div className="p-6 border-b border-white/10">
          <label className="block text-sm font-bold text-gray-300 mb-3">Export Format</label>
          <div className="flex gap-3">
            {(['txt', 'json', 'markdown'] as const).map((fmt) => (
              <button
                key={fmt}
                onClick={() => setFormat(fmt)}
                className={`px-6 py-3 rounded-lg font-medium text-sm transition-all ${
                  format === fmt
                    ? 'bg-gradient-to-r from-cyan-500 to-blue-500 text-white shadow-lg scale-105'
                    : 'bg-white/5 text-gray-400 hover:bg-white/10 hover:text-white'
                }`}
              >
                {fmt.toUpperCase()}
              </button>
            ))}
          </div>
        </div>

        {/* Preview */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 bg-black/30">
          <div className="bg-slate-950 rounded-lg p-4 border border-white/10">
            <pre className="text-xs text-gray-300 font-mono whitespace-pre-wrap break-words">
              {getContent()}
            </pre>
          </div>
        </div>

        {/* Actions */}
        <div className="p-6 border-t border-white/10 flex gap-3">
          <button
            onClick={handleCopy}
            className="flex-1 bg-white/10 hover:bg-white/20 text-white py-3 rounded-xl font-bold transition-all flex items-center justify-center gap-2"
          >
            {copied ? (
              <>
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd"/>
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"/>
                </svg>
                Copy to Clipboard
              </>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex-1 bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-400 hover:to-blue-400 text-white py-3 rounded-xl font-bold shadow-lg transition-all flex items-center justify-center gap-2 hover:scale-105"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
            </svg>
            Download File
          </button>
        </div>
      </div>
    </div>
  );
};
